version: '3.9'

services:
    app:
        restart: unless-stopped
        build: .
        ports:
            - '${PORT}:${PORT}'
        environment:
            - PORT=${PORT}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_PORT=${DATABASE_PORT}
